services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - VITE_GRAPHQL_HTTP_URL=http://localhost:8080/api/graphql
      - VITE_GRAPHQL_WS_URL=ws://localhost:8080/api/graphql

  backend:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - ./backend/.env
    dns:
      - 8.8.8.8
      - 8.8.4.4

  nginx:
    image: nginx:1.29
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - frontend
      - backend
